version: "3.3"

services:
  blue-backend: &backend
    image: gitlab.praktikum-services.ru:5050/std-022-039/sausage-store/backend:${VERSION}
    container_name: blue-backend
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${PSQL_DATASOURCE}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      SPRING_DATA_MONGODB_URI: ${MONGO_DATA}
      VIRTUAL_HOST: sausage-store
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6
    networks:
      - sausage-store
    deploy:
      replicas: 1

  green-backend:
    <<: *backend
    container_name: green-backend
    restart: always
      
  backend-report:
    container_name: sausage-store-backend-report
    restart: always
    build:
      context: backend-report
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      DB: ${MONGO_DATA}
    networks:
      - sausage-store

  frontend:
    image: gitlab.praktikum-services.ru:5050/std-022-039/sausage-store/frontend:${VERSION}
    container_name: sausage-store-frontend
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: sausage-store
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store:
