version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-022-039/sausage-store/backend:${VERSION}
    container_name: sausage-store-backend
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${PSQL_DATASOURCE}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      SPRING_DATA_MONGODB_URI: ${DATA_MONGODB_URI}
    networks:
      - sausage-store

  backend-report:
    container_name: sausage-store-backend-report
    build:
      context: backend-report
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      DB: ${DATA_MONGODB_URI}
    networks:
      - sausage-store

  frontend:
    image: gitlab.praktikum-services.ru:5050/std-022-039/sausage-store/frontend:${VERSION}
    container_name: sausage-store-frontend
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store:
