include:
  - project: "templates/ci"
    file: "DockerInDockerTemplate.yml"
  - template: Security/SAST.gitlab-ci.yml

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  JAVA_OPTS: -XX:MaxRAMPercentage=90
  VERSION: 1.0.${CI_PIPELINE_ID}
  
stages:
  - build
  - test
  - notify
  - release
  - deploy

cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

build-backend-code-job:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "test"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/backend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true

release:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA $VERSION

spotbugs-sast:
  stage: test
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: "${CI_PROJECT_DIR}/.m2/repository"

sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  variables:
    GIT_DEPTH: "0"
  script:
    - mvn -f ${CI_PROJECT_DIR}/backend -X verify sonar:sonar -Dsonar.projectName="22_ДаниилПайдютов_БЭКЕНД" -Dsonar.projectKey=$SONAR_PROJECT_KEY_BACK -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONAR_LOGIN  -Dsonar.qualitygate.wait=true

telegram-notification-backend:
  stage: notify
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - |
     curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "-1001771539978", "text": "Backend project build for std-022-039. Checkout link below ", "parse_mode": "markdown", "reply_markup": {"inline_keyboard": [[{"text": "@GrantRusov", "url": "'"$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build-backend-code-job"'"}]]}}' $TELEGRAM_NOTIFY_API
  needs:
    - build-backend-code-job

deploy:
  stage: deploy
  image: alpine:3.18
  before_script:
    - apk add openssh-client bash docker docker-compose
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - docker context create remote --docker "host=ssh://$DEV_USER@$DEV_HOST"
    - docker context use remote
    - >
      export SPRING_DATASOURCE_URL=${PSQL_DATASOURCE}
      export SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      export SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      export DATA_MONGODB_URI=${MONGO_DATA}
      export IMAGE_BACKEND=${IMAGE_BACKEND}:${VERSION}
      export CI_REGISTRY_USER=${CI_REGISTRY_USER}
      export CI_REGISTRY_PASSWORD=${CI_REGISTRY_PASSWORD}
      export CI_REGISTRY=${CI_REGISTRY}
      export SPRING_FLYWAY_ENABLED=false
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose --context remote up -d backend