include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

build-backend-code-job:
  stage: build
  only:
    changes:
    - backend/**/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar

spotbugs-sast:
  stage: test
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: "${CI_PROJECT_DIR}/.m2/repository"

sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  variables:
    GIT_DEPTH: "0"
  script:
    - mvn -f ${CI_PROJECT_DIR}/backend -X verify sonar:sonar -Dsonar.projectName="22_Даниил_БЭКЕНД" -Dsonar.projectKey=$SONAR_PROJECT_KEY_BACK -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONAR_LOGIN  -Dsonar.qualitygate.wait=true

telegram-notification-backend:
  stage: notify
  only:
    changes:
    - backend/**/*
    variables:
    - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - |
     curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "-1001771539978", "text": "Backend project build for std-022-039. Checkout link below ", "parse_mode": "markdown", "reply_markup": {"inline_keyboard": [[{"text": "@GrantRusov", "url": "'"$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build-backend-code-job"'"}]]}}' https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage
  needs:
    - build-backend-code-job
