---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  revisionHistoryLimit: 15
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        app: frontend
      containers:
        - name: frontend
          image: gitlab.praktikum-services.ru:5050/std-022-039/sausage-store/frontend:${VERSION}
          imagePullPolicy: IfNotPresent
          ports:
            - name: frontend
              containerPort: 80
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/dashboard.conf
            subPath: dashboard.conf
      volumes:
      - name: nginx-config
        configMap:
          name: sausagestore-configmap
      imagePullSecrets:
        - name: docker-config-secret
