include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.22.6
  environment:
    name: k8s
    url: http://std-022-39.praktikum-services.tech
  before_script:
    - rm -rf ~/.kube || true
    - mkdir -p ~/.kube || true
    - cp ./kubernetes/config ~/.kube/
  script:
    - kubectl apply -f kubernetes/frontend --recursive --kubeconfig ~/.kube/config
    - kubectl apply -f kubernetes/backend --recursive -kubeconfig ~/.kube/config
    - kubectl apply -f kubernetes/backend-report --recursive --kubeconfig ~/.kube/config
    - rm ~/.kube/config