include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.22.6
  environment:
    name: k8s
    url: http://std-022-39.praktikum-services.tech
  script:
    - kubectl apply -f kubernetes/frontend --kubeconfig ~/.kube/config
    - kubectl apply -f kubernetes/backend --kubeconfig ~/.kube/config
    - kubectl apply -f kubernetes/backend-report --kubeconfig ~/.kube/config
    - rm ~/.kube/config