---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausage-store-backend-report
  labels:
    app: sausage-store-backend-report
spec:
  replicas: 3
  # Стратегия развёртывания. Recreate — удалит сначала все старые поды 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять поды порциями  
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sausage-store-backend-report
  template:
    metadata:
      labels:
        app: sausage-store-backend-report
    spec:
      containers:
        - name: sausage-store-backend-report
          image: gitlab.praktikum-services.ru:5050/std-022-039/sausage-store/sausage-backend-report:latest
          imagePullPolicy: IfNotPresent
          # env:
          #   - name: VAULT_HOST
          #     value: 130.193.38.73
          #   - name: VAULT_TOKEN
          #     valueFrom:
          #       secretKeyRef:
          #         name: vault
          #         key: vault_token
          ports:
            - name: backend-report
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret